[package]
name = "rust_encrypt_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chacha20poly1305 = { version = "0.10", features = ["xchacha20"] }
rand_core = "0.6"
base64 = "0.21"
